version: '3.4'

services:
  workstation:
    image: workstation
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - '/home/user/.Xauthority:/home/project/.Xauthority'
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./gcode/:/home/project/gcode
    entrypoint: ./flatcam
    
  cncjs:
    image: pcbmill-cncjs
    build: 
      context: .
      dockerfile: pcbmill-cncjs.dockerfile
    restart: always
    ports:
      - 8000:8000
    group_add:
      - dialout
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    entrypoint: node . --port /dev/ttyUSB0 -c .cncrc
