version: '3.4'

services:
  workstation:
    image: workstation
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - '/home/user/.Xauthority:/home/project/.Xauthority'
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./gcode/:/home/project/gcode
    entrypoint: ./flatcam
